"""Obsidian LiveSync passphrase.

Self-Hosted LiveSync uses CouchDB on the VM with end-to-end encryption.
We generate (or accept) a passphrase here; the operator will paste the same
passphrase into the LiveSync plugin on their phone/laptop later.

Writes:
  state["livesync_passphrase"]  (sensitive)
  state["livesync_admin_user"]
  state["livesync_admin_pass"]  (sensitive)
"""

from __future__ import annotations

# TODO:
#   - offer to auto-generate a strong passphrase, or paste one
#   - generate CouchDB admin user/pass
#   - explain that the operator will need to install the
#     "Self-hosted LiveSync" Obsidian plugin on their devices and configure:
#       URI: https://<tailscale-ip>:5984 (or the vault's tailnet hostname)
#       Database: obsidian
#       Username/Password: <auto-generated above>
#       Passphrase: <auto-generated above>


def run(state: dict) -> None:
    raise NotImplementedError("TODO: Obsidian LiveSync setup")
